class School21Error(Exception): ...


# TODO: rename
class InvalidCallbackData(Exception): ...


# TODO: make base class with messages and input as arg
class InvalidUserInput(Exception): ...


class BotNotFound(Exception): ...


class InternalError(Exception): ...
