query getLocalCourseGoals($localCourseId: ID!) {
    course {
        getLocalCourseGoals(localCourseId: $localCourseId) {
            localCourseId
            globalCourseId
            courseName
            courseType
            localCourseGoals {
                ...LocalCourse
                __typename
            }
            __typename
        }
        __typename
    }
}
fragment LocalCourse on LocalCourseGoalInformation {
    localCourseGoalId
    goalId
    goalName
    description
    projectHours
    signUpDate
    beginDate
    deadlineDate
    checkDate
    isContentAvailable
    executionType
    finalPoint
    finalPercentage
    status
    periodSettings
    retriesUsed
    statusUpdateDate
    retrySettings {
        ...RetrySettings
        __typename
    }
    __typename
}
fragment RetrySettings on ModuleAttemptsSettings {
    maxModuleAttempts
    isUnlimitedAttempts
    __typename
}