query getProjectInfo($goalId: ID!, $studentId: UUID!) {
    school21 {
        getModuleById(goalId: $goalId, studentId: $studentId) {
            ...ProjectInfo
            __typename
        }
        getModuleCoverInformation(goalId: $goalId, studentId: $studentId) {
            ...ModuleCoverInfo
            __typename
        }
        getP2PChecksInfo(goalId: $goalId, studentId: $studentId) {
            ...P2PInfo
            __typename
        }
        getStudentCodeReviewByGoalId(goalId: $goalId, studentId: $studentId) {
            ...StudentsCodeReview
            __typename
        }
        __typename
    }
}

fragment ProjectInfo on StudentModule {
    id
    moduleTitle
    finalPercentage
    finalPoint
    goalExecutionType
    displayedGoalStatus
    accessBeforeStartProgress
    resultModuleCompletion
    finishedExecutionDateByScheduler
    durationFromStageSubjectGroupPlan
    currentAttemptNumber
    isDeadlineFree
    isRetryAvailable
    localCourseId
    courseBaseParameters {
        isGradedCourse
        __typename
    }
    teamSettings {
        ...teamSettingsInfo
        __typename
    }
    studyModule {
        id
        idea
        duration
        goalPoint
        retrySettings {
            ...RetrySettings
            __typename
        }
        levels {
            id
            goalElements {
                id
                tasks {
                    id
                    taskId
                    __typename
                }
                __typename
            }
            __typename
        }
        __typename
    }
    currentTask {
        ...CurrentInternshipTaskInfo
        __typename
    }
    __typename
}

fragment teamSettingsInfo on TeamSettings {
    teamCreateOption
    minAmountMember
    maxAmountMember
    enableSurrenderTeam
    __typename
}

fragment RetrySettings on ModuleAttemptsSettings {
    maxModuleAttempts
    isUnlimitedAttempts
    __typename
}

fragment CurrentInternshipTaskInfo on StudentTask {
    id
    taskId
    task {
        id
        assignmentType
        taskSolutionType
        studentTaskAdditionalAttributes {
            cookiesCount
            maxCodeReviewCount
            codeReviewCost
            ciCdMode
            __typename
        }
        checkTypes
        taskSolutionType
        __typename
    }
    lastAnswer {
        id
        __typename
    }
    teamSettings {
        ...teamSettingsInfo
        __typename
    }
    __typename
}

fragment ModuleCoverInfo on ModuleCoverInformation {
    isOwnStudentTimeline
    softSkills {
        softSkillId
        softSkillName
        totalPower
        maxPower
        currentUserPower
        achievedUserPower
        teamRole
        __typename
    }
    timeline {
        ...TimelineItem
        __typename
    }
    __typename
}

fragment TimelineItem on ProjectTimelineItem {
    type
    status
    start
    end
    children {
        ...TimelineItemChildren
        __typename
    }
    __typename
}

fragment TimelineItemChildren on ProjectTimelineItem {
    type
    elementType
    status
    start
    end
    order
    __typename
}

fragment P2PInfo on P2PChecksInfo {
    cookiesCount
    periodOfVerification
    projectReviewsInfo {
        ...ProjectReviewsInfo
        __typename
    }
    __typename
}

fragment ProjectReviewsInfo on ProjectReviewsInfo {
    reviewByStudentCount
    relevantReviewByStudentsCount
    reviewByInspectionStaffCount
    relevantReviewByInspectionStaffCount
    p2pRequirementStatus
    __typename
}

fragment StudentsCodeReview on StudentCodeReviewsWithCountRound {
    countRound1
    countRound2
    codeReviewsInfo {
        maxCodeReviewCount
        codeReviewDuration
        codeReviewCost
        __typename
    }
    __typename
}